// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace FDB.Mod
{
    public  class CommentsDto
    {
        public Guid User_Id { get; set; }
        public string Comment { get; set; }
        public Guid Publication_Id { get; set; }
        public Guid Comment_Id { get; set; } = Guid.NewGuid();
        public DateTime? Date { get; set; } = DateTime.Now;
    }
}