// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FDB.Mod
{
    public partial class ClientsDto
    {
        public Guid User_Id { get; set; } = Guid.NewGuid();
        public string Nom { get; set; }
        public string Prenom { get; set; }
    }
}